sudo: required

language: cpp
services:
  - docker

before_install:
  # ubuntu bionic
  - wget -nv -c https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-i386/wine-stable_${WS_VER}~bionic_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-i386/wine-stable-i386_${WS_VER}~bionic_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-i386/wine-devel_${WDEV_VER}~bionic_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-i386/wine-devel-i386_${WDEV_VER}~bionic_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-i386/wine-staging_${WSTG_VER}~bionic_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-i386/wine-staging-i386_${WSTG_VER}~bionic_i386.deb

  # debian buster
  - wget -nv -c https://dl.winehq.org/wine-builds/debian/dists/buster/main/binary-i386/wine-stable_4.0~buster_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/debian/dists/buster/main/binary-i386/wine-stable-i386_4.0~buster_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/debian/dists/buster/main/binary-i386/wine-devel_4.3~buster_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/debian/dists/buster/main/binary-i386/wine-devel-i386_4.3~buster_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/debian/dists/buster/main/binary-i386/wine-staging_4.3~buster_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/debian/dists/buster/main/binary-i386/wine-staging-i386_4.3~buster_i386.deb

  # debian stretch
  - wget -nv -c https://dl.winehq.org/wine-builds/debian/dists/stretch/main/binary-i386/wine-stable_4.0~stretch_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/debian/dists/stretch/main/binary-i386/wine-stable-i386_4.0~stretch_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/debian/dists/stretch/main/binary-i386/wine-devel_4.3~stretch_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/debian/dists/stretch/main/binary-i386/wine-devel-i386_4.3~stretch_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/debian/dists/stretch/main/binary-i386/wine-staging_4.3~stretch_i386.deb
  - wget -nv -c https://dl.winehq.org/wine-builds/debian/dists/stretch/main/binary-i386/wine-staging-i386_4.3~stretch_i386.deb

  # appimagetool
  - wget -nv -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" -O  appimagetool.AppImage

script:
  # ubuntu bionic
  - docker build . -f deploydocker/Dockerfile.wine-stable-deploy.bionic -t wine-stable-appimage.bionic
  - docker build . -f deploydocker/Dockerfile.wine-devel-deploy.bionic -t wine-devel-appimage.bionic
  - docker build . -f deploydocker/Dockerfile.wine-staging-deploy.bionic -t wine-staging-appimage.bionic

  # debian buster
  # - docker build . -f deploydocker/Dockerfile.wine-stable-deploy.buster -t wine-stable-appimage.buster
  # - docker build . -f deploydocker/Dockerfile.wine-devel-deploy.buster -t wine-devel-appimage.buster
  # - docker build . -f deploydocker/Dockerfile.wine-staging-deploy.buster -t wine-staging-appimage.buster

  # debian stretch
  # - docker build . -f deploydocker/Dockerfile.wine-stable-deploy.stretch -t wine-stable-appimage.stretch
  # - docker build . -f deploydocker/Dockerfile.wine-devel-deploy.stretch -t wine-devel-appimage.stretch
  # - docker build . -f deploydocker/Dockerfile.wine-staging-deploy.stretch -t wine-staging-appimage.stretch

  # archlinux
  # - docker build . -f deploydocker/Dockerfile.winedeploy.arch.latest -t wineappimage.arch.latest

after_success:
  - mkdir apps

  # ubuntu bionic
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-stable-appimage.bionic cp Wine-x86_64.AppImage /tmp/apps/Wine-stable-x86_64-bionic.AppImage
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-stable-appimage.bionic cp Wine-x86_64.AppImage.zsync /tmp/apps/Wine-stable-x86_64-bionic.AppImage.zsync
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-devel-appimage.bionic cp Wine-x86_64.AppImage /tmp/apps/Wine-devel-x86_64-bionic.AppImage
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-devel-appimage.bionic cp Wine-x86_64.AppImage.zsync /tmp/apps/Wine-devel-x86_64-bionic.AppImage.zsync
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-staging-appimage.bionic cp Wine-x86_64.AppImage /tmp/apps/Wine-staging-x86_64-bionic.AppImage
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-staging-appimage.bionic cp Wine-x86_64.AppImage.zsync /tmp/apps/Wine-staging-x86_64-bionic.AppImage.zsync

  # debian buster
  # - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-stable-appimage.buster cp Wine-x86_64.AppImage /tmp/apps/Wine-stable-x86_64-buster.AppImage
  # - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-stable-appimage.buster cp Wine-x86_64.AppImage.zsync /tmp/apps/Wine-stable-x86_64-buster.AppImage.zsync
  # - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-devel-appimage.buster cp Wine-x86_64.AppImage /tmp/apps/Wine-devel-x86_64-buster.AppImage
  # - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-devel-appimage.buster cp Wine-x86_64.AppImage.zsync /tmp/apps/Wine-devel-x86_64-buster.AppImage.zsync
  # - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-staging-appimage.buster cp Wine-x86_64.AppImage /tmp/apps/Wine-staging-x86_64-buster.AppImage
  # - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-staging-appimage.buster cp Wine-x86_64.AppImage.zsync /tmp/apps/Wine-staging-x86_64-buster.AppImage.zsync

  # debian stretch
  # - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-stable-appimage.stretch cp Wine-x86_64.AppImage /tmp/apps/Wine-stable-x86_64-stretch.AppImage
  # - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-stable-appimage.stretch cp Wine-x86_64.AppImage.zsync /tmp/apps/Wine-stable-x86_64-stretch.AppImage.zsync
  # - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-devel-appimage.stretch cp Wine-x86_64.AppImage /tmp/apps/Wine-devel-x86_64-stretch.AppImage
  # - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-devel-appimage.stretch cp Wine-x86_64.AppImage.zsync /tmp/apps/Wine-devel-x86_64-stretch.AppImage.zsync
  # - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-staging-appimage.stretch cp Wine-x86_64.AppImage /tmp/apps/Wine-staging-x86_64-stretch.AppImage
  # - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-staging-appimage.stretch cp Wine-x86_64.AppImage.zsync /tmp/apps/Wine-staging-x86_64-stretch.AppImage.zsync

  # archlinux
  # - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wineappimage.arch.latest cp Wine-x86_64.AppImage /tmp/apps/Wine-x86_64-arch.latest.AppImage
  
  # uploadtool
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh apps/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/